[build]
  publish = "out"
  command = "rm -rf node_modules && npm install --legacy-peer-deps && npx next build"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_REGISTRY = "https://registry.npmjs.org/"
  NPM_CONFIG_TIMEOUT = "600000"
  NPM_CONFIG_FETCH_TIMEOUT = "600000"
  NPM_CONFIG_PROGRESS = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
