[build]
  publish = "out"
  command = "npm install --no-optional --legacy-peer-deps --verbose && npm ls && npx next build"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NPM_CONFIG_REGISTRY = "https://registry.npmjs.org/"
  NPM_REGISTRY = "https://registry.npmjs.org/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
