[build]
  publish = "out"
  command = "rm -rf node_modules package-lock.json && npm install --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "10.2.4"
  NPM_FLAGS = "--prefer-offline --no-audit"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
