[build]
  publish = "out"
  command = "npm ci --prefer-offline --no-audit --legacy-peer-deps --timeout=300000 && npx next build"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_REGISTRY = "https://registry.npmjs.org/"
  NPM_CONFIG_TIMEOUT = "300000"
  NPM_CONFIG_FETCH_TIMEOUT = "300000"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
